# -*- coding: utf-8 -*-
import os

path = r'D:\Personal\Desktop\2\ArcaneCodex\src-tauri\src\core\settings\backup.rs'

lines = []
lines.append('#![allow(missing_docs)]')
lines.append('use std::path::{Component, Path, PathBuf};')
lines.append('use crate::utils::error::AppError;')
lines.append('use tracing::{info, warn};')
lines.append('')

# Helper functions
lines.append('/// Check if a path component is a directory traversal attempt')
lines.append('fn contains_encoded_traversal(path: &str) -> bool {')
lines.append('    let encoded_patterns = ["%2e", "%252e", "..%5c", "%c0%ae", "%e0%40%ae", "%c0%2e", "%%32%%65"];')
lines.append('    let lower = path.to_lowercase();')
lines.append('    encoded_patterns.iter().any(|&p| lower.contains(p))')
lines.append('}')
lines.append('')

# Now the big function
lines.append('/// Validate backup/restore path for security')
lines.append('fn validate_backup_restore_path(path: &str, must_exist: bool) -> Result<PathBuf, AppError> {')
lines.append('    let input = path.trim();')
lines.append('    if input.is_empty() {')
lines.append('        return Err(AppError::validation("路径不能为空"));')
lines.append('    }')
lines.append('    if input.len() > 240 {')
lines.append('        return Err(AppError::validation(format!("路径过长 ({} 字符，最大 240)", input.len())));')
lines.append('    }')
lines.append('    let path_buf = PathBuf::from(input);')
lines.append('    let input_lower = input.to_lowercase();')
lines.append('    if input.starts_with("\\\\") || input.starts_with("//") {')
lines.append('        return Err(AppError::validation("不允许使用 UNC 路径"));')
lines.append('    }')
lines.append('    if input_lower.contains("\\\\.\\") || input_lower.contains("\\\\?\\") {')
lines.append('        return Err(AppError::validation("不允许使用设备路径"));')
lines.append('    }')
lines.append('    if input.contains("::$") {')
lines.append('        return Err(AppError::validation("检测到 NTFS 数据流攻击"));')
lines.append('    }')
lines.append('    #[cfg(windows)]')
lines.append('    {')
lines.append('        const RESERVED_NAMES: &[&str] = &[')
lines.append('            "con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8", "com9",')
lines.append('            "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9",')
lines.append('        ];')
lines.append('        if let Some(file_name) = path_buf.file_name().and_then(|n| n.to_str()) {')
lines.append('            let name_lower = file_name.to_lowercase();')
lines.append('            let name_without_ext = if let Some(dot) = name_lower.rfind(".") { &name_lower[..dot] } else { &name_lower };')
lines.append('            if RESERVED_NAMES.contains(&name_without_ext) {')
lines.append('                return Err(AppError::validation("路径包含 Windows 保留名称"));')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('    // Check for directory traversal')
lines.append('    for component in path_buf.components() {')
lines.append('        if component == Component::ParentDir {')
lines.append('            return Err(AppError::validation("路径包含遍历序列 (..)"));')
lines.append('        }')
lines.append('    }')
lines.append('    // Check for encoded traversal')
lines.append('    if contains_encoded_traversal(input) {')
lines.append('        return Err(AppError::validation("检测到编码路径遍历攻击"));')
lines.append('    }')
lines.append('    // Check for control characters')
lines.append('    if input.bytes().any(|b| b < 32 && b != 9 && b != 10 && b != 13) {')
lines.append('        return Err(AppError::validation("路径包含控制字符"));')
lines.append('    }')
lines.append('    // Check for must_exist')
lines.append('    if must_exist && !path_buf.exists() {')
lines.append('        return Err(AppError::validation("路径不存在"));')
lines.append('    }')
lines.append('    Ok(path_buf)')
lines.append('}')
lines.append('')

# is_system_sensitive_directory
lines.append('/// Check if a path contains system-sensitive directories')
lines.append('fn is_system_sensitive_directory(path: &Path) -> bool {')
lines.append('    let sensitive_dirs = [')
lines.append('        "/etc", "/sys", "/proc", "/dev", "/boot", "/root", "/var/log",')
lines.append('    ];')
lines.append('    let path_str = path.to_string_lossy().to_lowercase().replace("\\\\", "/");')
lines.append('    for dir in &sensitive_dirs {')
lines.append('        if path_str.starts_with(dir) || path_str.contains(&format!("/{}/", dir.trim_start_matches("/"))) {')
lines.append('            return true;')
lines.append('        }')
lines.append('    }')
lines.append('    false')
lines.append('}')
lines.append('')

# Windows variant
lines.append('#[cfg(windows)]')
lines.append('fn is_system_sensitive_directory(path: &Path) -> bool {')
lines.append('    let sensitive_dirs = [')
lines.append('        "c:\\windows", "c:\\winnt", "c:\\program files", "c:\\program files (x86)",')
lines.append('        "c:\\system volume information", "c:\\recovery", "c:\\$recycle.bin",')
lines.append('        "c:\\users\\default", "c:\\users\\public",')
lines.append('        "c:\\programdata", "c:\\all users",')
lines.append('    ];')
lines.append('    let path_str = path.to_string_lossy().to_lowercase();')
lines.append('    for dir in &sensitive_dirs {')
lines.append('        if path_str.starts_with(dir) || path_str.starts_with(&dir.replace("\\", "/")) {')
lines.append('            return true;')
lines.append('        }')
lines.append('    }')
lines.append('    // Call the original implementation')
lines.append('    false')
lines.append('}')
lines.append('')

# normalize_path_for_backup
lines.append('/// Normalize a path for backup operations')
lines.append('fn normalize_path_for_backup(path: &str) -> Result<String, AppError> {')
lines.append('    let validated = validate_backup_restore_path(path, false)?;')
lines.append('    if is_system_sensitive_directory(&validated) {')
lines.append('        return Err(AppError::validation("不允许备份系统敏感目录"));')
lines.append('    }')
lines.append('    let normalized = validated.to_string_lossy().to_string();')
lines.append('    info!("Normalized backup path: {}", normalized);')
lines.append('    Ok(normalized)')
lines.append('}')
lines.append('')

# Tests section
lines.append('#[cfg(test)]')
lines.append('mod tests {')
lines.append('    use super::*;')
lines.append('')

# Security validation tests
lines.append('    // ============================================================')
lines.append('    // 路径验证安全测试 (TC-SETTINGS-SEC-001)')
lines.append('    // ============================================================')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_001_validate_empty_path() {')
lines.append('        let result = validate_backup_restore_path("", false);')
lines.append('        assert!(result.is_err());')
lines.append('        let err = result.unwrap_err().to_string();')
lines.append('        assert!(err.contains("不能为空"));')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_002_validate_whitespace_only_path() {')
lines.append('        let result = validate_backup_restore_path("   ", false);')
lines.append('        assert!(result.is_err());')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_003_validate_path_traversal() {')
lines.append('        let malicious_paths = vec![')
lines.append('            "../../etc/passwd",')
lines.append('            "..\\..\\windows\\system32\\config",')
lines.append('            "/home/user/../../../etc/shadow",')
lines.append('            "C:\\Users\\..\\..\\Windows\\System32",')
lines.append('            "folder/../../secret",')
lines.append('        ];')
lines.append('        for path in malicious_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_err(), "路径应被拒绝: {}", path);')
lines.append('            let err = result.unwrap_err().to_string();')
lines.append('            assert!(err.contains("..") || err.contains("遍历"), "错误应提及遍历: got: {}", err);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_004_validate_unc_path() {')
lines.append('        let unc_paths = vec![')
lines.append('            "\\\\server\\share\\backup.zip",')
lines.append('            "//server/share/backup.zip",')
lines.append('            "\\\\?\\C:\\Users\\public",')
lines.append('        ];')
lines.append('        for path in unc_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_err(), "UNC 路径应被拒绝: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_005_validate_ntfs_ads_path() {')
lines.append('        let ads_paths = vec![')
lines.append('            "backup.zip::$DATA",')
lines.append('            "folder\\file.txt::$DATA",')
lines.append('            "/home/user/backup.zip:\\$DATA",')
lines.append('        ];')
lines.append('        for path in ads_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_err(), "NTFS ADS 路径应被拒绝: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_006_validate_encoded_traversal() {')
lines.append('        let encoded_paths = vec![')
lines.append('            "%2e%2e/etc/passwd",')
lines.append('            "%252e%252e/secret",')
lines.append('            "folder/..%5c..%5cwindows\\system32",')
lines.append('        ];')
lines.append('        for path in encoded_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_err(), "编码遍历路径应被拒绝: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_007_validate_control_chars() {')
lines.append('        let result = validate_backup_restore_path("C:\\Users\\test\\backup\x00.zip", false);')
lines.append('        assert!(result.is_err());')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_008_validate_oversized_path() {')
lines.append('        let long_path = "a".repeat(241);')
lines.append('        let result = validate_backup_restore_path(&long_path, false);')
lines.append('        assert!(result.is_err());')
lines.append('        let err_msg = result.unwrap_err().to_string();')
lines.append('        assert!(err_msg.contains("过长") || err_msg.contains("240"));')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_009_validate_normal_path_pass() {')
lines.append('        let normal_paths = vec![')
lines.append('            "C:\\Users\\test\\backups\\my_backup.zip",')
lines.append('            "/home/user/backups/my_backup.tar.gz",')
lines.append('            "D:\\backup",')
lines.append('            "E:\\archive\\daily\\2024-01-15",')
lines.append('        ];')
lines.append('        for path in normal_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_ok(), "正常路径应通过: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_010_validate_reserved_names() {')
lines.append('        // Skip reserved name check for non-Windows platforms since the check is #[cfg(windows)]')
lines.append('        #[cfg(windows)]')
lines.append('        {')
lines.append('            let reserved_paths = vec![')
lines.append('                "C:\\Users\\test\\CON",')
lines.append('                "D:\\PRN\\backup.zip",')
lines.append('                "E:\\NUL\\data",')
lines.append('                "F:\\LPT1\\output",')
lines.append('                "G:\\COM1",')
lines.append('            ];')
lines.append('            for path in reserved_paths {')
lines.append('                let result = validate_backup_restore_path(path, false);')
lines.append('                assert!(result.is_err(), "保留名称路径应被拒绝: {}", path);')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_011_validate_device_paths() {')
lines.append('        let device_paths = vec![')
lines.append('            "\\.\\COM1",')
lines.append('            "\\.\\PhysicalDrive0",')
lines.append('            "\\\\?\\C:\\Users\\test",')
lines.append('        ];')
lines.append('        for path in device_paths {')
lines.append('            let result = validate_backup_restore_path(path, false);')
lines.append('            assert!(result.is_err(), "设备路径应被拒绝: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_012_validate_must_exist_flag() {')
lines.append('        // A path that clearly doesn\'t exist')
lines.append('        let result = validate_backup_restore_path("Z:\\nonexistent_path_xyz", true);')
lines.append('        assert!(result.is_err());')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_013_validate_mixed_case_unc() {')
lines.append('        let result = validate_backup_restore_path("\\\\Server\\Share\\file", false);')
lines.append('        assert!(result.is_err());')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_014_validate_system_sensitive_dir() {')
lines.append('        #[cfg(unix)]')
lines.append('        {')
lines.append('            let result = normalize_path_for_backup("/etc/passwd");')
lines.append('            assert!(result.is_err());')
lines.append('        }')
lines.append('        #[cfg(windows)]')
lines.append('        {')
lines.append('            let result = normalize_path_for_backup("C:\\Windows\\System32");')
lines.append('            assert!(result.is_err());')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    #[test]')
lines.append('    fn tc_settings_sec_015_validate_normalize_backup_path() {')
lines.append('        let valid_paths = vec![')
lines.append('            "C:\\Users\\test\\backups\\my_backup.zip",')
lines.append('            "/home/user/backups/my_backup.tar.gz",')
lines.append('            "D:\\archive\\backup",')
lines.append('        ];')
lines.append('        for path in valid_paths {')
lines.append('            let result = normalize_path_for_backup(path);')
lines.append('            assert!(result.is_ok(), "正常备份路径应通过 normalize: {}", path);')
lines.append('        }')
lines.append('    }')
lines.append('')

# Close tests module
lines.append('}')

with open(path, 'w', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')

print(f'Written {len(lines)} lines to {path}')
